CREATE TABLE Monster (
  ID integer NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  SIZE integer,
  PRIMARY KEY (ID)
);
CREATE TABLE Damage (
  MONSTERID integer NOT NULL,
  ATTACK integer,
  MULTIPLIER integer,
  PRIMARY KEY (MONSTERID, ATTACK)
);
ALTER TABLE Damage
ADD CONSTRAINT Damage_Monster
FOREIGN KEY (MONSTERID) REFERENCES Monster;
